#!/bin/bash
#May need to change /usr/bin/google-chrome to a soft link pointing at \
#/opt/google/chrome/google-chrome

if [[ -e /opt/google/chrome/google-chrome ]]; then
	grep -v exec /opt/google/chrome/google-chrome > gchrome
	echo 'exec -a "$0" "$HERE/chrome" "$@" --user-data-dir' >> gchrome
	mv gchrome /opt/google/chrome/google-chrome
	chmod +x /opt/google/chrome/google-chrome
fi

